# Generated by Django 5.2.6 on 2025-10-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ITEM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_name', models.CharField(max_length=150, verbose_name='professor_name')),
                ('school_name', models.CharField(max_length=150, verbose_name='school_name')),
                ('department_name', models.CharField(max_length=150, verbose_name='department_name')),
                ('star_rating', models.FloatField(verbose_name='star_rating')),
                ('course', models.CharField(max_length=150, verbose_name='name_not_onlines')),
                ('difficulty', models.IntegerField(verbose_name='student_difficult')),
                ('would_take_agains', models.BooleanField(default=False, verbose_name='would_take_agains')),
                ('help_useful', models.IntegerField(verbose_name='help_useful')),
                ('comments', models.CharField(max_length=255, verbose_name='comments')),
            ],
            options={
                'db_table': 'ITEM',
            },
        ),
    ]
